micronaut:
  application:
    name: cinephile
  server:
    port: 80
datasources:
  default:
    url: jdbc:tc:postgresql:9.6.8:///cinephile
    username: admin
    password: admin
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: none
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
    entity-scan:
      packages: 'co.incubyte'
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.sql'

